
library:
  # Selfexplained folders
  BOOK_STOCK: "books/stock"
  NEW_ACQUISITIONS: "books/new"
  TRASH: "books/trash"

language:
  # English, can be changed to "ru" for Russian opds feeds (bookreaders opds menu tree)
  DEFAULT: "en"  

database:
  DSN: "dbdata/flglt.db"
  INIT_SCRIPT: "config/sqlite_db_init.sql"
  DROP_SCRIPT: "config/sqlite_db_drop.sql"
  # New aqusitions processing period
  POLL_PERIOD: 30 
  # Maximum simultaneous new aquisitios processing threads
  MAX_SCAN_THREADS: 3
  # Process only this languages puplications
  ACCEPTED_LANGS: "en,ru"

genres:
  TREE_FILE: "config/genres.xml"
  # Alternative genres can be used (Russian only, sorry) 
  # TREE_FILE: "config/alt_genres.xml"
  
logs:
  # Logs are here
  OPDS: "logs/opds.log"
  SCAN: "logs/scan.log"
  DEBUG: false

opds:
  # OPDS-server port
  PORT: 8085
  # OPDS feeds entries page size
  PAGE_SIZE: 30

